preserve_hierarchy: true

files:
  - source: /localization/crowdin/source.csv
    translation: /localization/crowdin/translations/%locale%.csv
    first_line_contains_header: true
    scheme: identifier,source_phrase,translation,context
    update_option: update_as_unapproved
    skip_untranslated_strings: true
