<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWPF>true</UseWPF>
    <PlatformTarget>x64</PlatformTarget>
    <Prefer32Bit>false</Prefer32Bit>
    <LangVersion>latest</LangVersion>
    <AssemblyName>TrackSwap</AssemblyName>
    <RootNamespace>TrackSwap</RootNamespace>
    <AssemblyTitle>TrackSwap</AssemblyTitle>
    <Product>TrackSwap v006</Product>
    <Description>SteamVR 位姿映射管理工具</Description>
    <Authors>Hrenact</Authors>
    <Copyright>Copyright © 2026 Hrenact</Copyright>
    <AssemblyVersion>0.0.6.0</AssemblyVersion>
    <FileVersion>0.0.6.0</FileVersion>
    <InformationalVersion>v006</InformationalVersion>
    <ApplicationIcon>Assets\TrackSwap.ico</ApplicationIcon>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TrackSwap.Protocol\TrackSwap.Protocol.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\TrackSwap.ico" />
    <Content Include="TrackSwap.vrmanifest">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <None Include="Assets\TrackSwap.svg" />
    <None Include="Assets\TrackSwap-16.png" />
    <None Include="Assets\TrackSwap-24.png" />
    <None Include="Assets\TrackSwap-32.png" />
    <None Include="Assets\TrackSwap-48.png" />
    <None Include="Assets\TrackSwap-64.png" />
    <None Include="Assets\TrackSwap-128.png" />
    <None Include="Assets\TrackSwap-256.png" />
    <None Include="Assets\TrackSwap-1024.png" />
  </ItemGroup>
</Project>
